CREATE OR REPLACE VIEW FTR00001 AS
 SELECT A.CD_FIL, 
        C.NM_RAZAO NM_RAZAO_FIL,
        C.NR_CGC NR_CGC_FIL,        
        C1.NM_CIDADE NM_CIDADE_FIL,
        C2.SG_ESTADO UF_FIL,
        C1.DS_BAIRRO DS_BAIRRO_FIL,
        C1.DS_LOGRADOURO DS_lOGRADOURO_FIL,
        C1.NR_LOGRADOURO NR_LOGRADOURO_FIL,
        C1.NR_CEP NR_CEP_FIL,
        C1.NR_TELEFONE NR_TELEFONE_FIL,
        A.NR_VENDA,
        A.DT_VENDA,
        A.CD_PESSOA_CLIENTE,
        D.NM_RAZAO NM_RAZAO_CLI,
        D.NR_CPF_CGC NR_CPF_CGC_CLI,        
        D1.NM_CIDADE NM_CIDADE_CLI,
        D2.SG_ESTADO UF_CLI, 
        D1.DS_BAIRRO DS_BAIRRO_CLI,
        D1.DS_LOGRADOURO DS_LOGRADOURO_CLI,
        D1.NR_LOGRADOURO NR_LOGRADOURO_CLI,
        D1.NR_CEP NR_CEP_CLI,
        D1.NR_TELEFONE NR_TELEFONE_CLI,
        A.CD_PESSOA_VENDEDOR,
        E.NM_RAZAO,
        A.NM_USUINC,
        B.CD_ITEM,
        F.DS_ITEM,
        F.CD_UNIMED,
        B.QT_ITEM,
        B.VL_ITEM
   FROM FTMESVEN A,
        FTITEVEN B,
        GEFILIAL C,
        GEENDERE C1,
        GECIDADE C2,
        GEPESSOA D,
        GEENDERE D1,
        GECIDADE D2,
        GEPESSOA E,
        ESITEMES F
  WHERE A.CD_FIL   = B.CD_FIL
    AND A.NR_VENDA = B.NR_VENDA
    AND A.CD_FIL   = C.CD_FIL
    AND C.CD_FIL   = C1.CD_FIL
    AND C1.NM_CIDADE = C2.NM_CIDADE
    AND A.CD_PESSOA_CLIENTE = D.CD_PESSOA(+)
    AND D.CD_PESSOA = D1.CD_PESSOA(+)
    AND D1.NM_CIDADE = D2.NM_CIDADE(+)
    AND A.CD_PESSOA_VENDEDOR = E.CD_PESSOA(+)
    AND B.CD_ITEM = F.CD_ITEM

